# Update Baseline Database

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- template: templates/variables.yml
- group: MySQL Admin Credentials

steps:
- script: echo Updating Baseline Database
  displayName: 'Description'

- task: FlywayInstaller@0
  inputs:
    flywayVersion: '6.2.0'

- task: FlywayCLI@0
  inputs:
    command: 'info'
    url: ${{variables.baseline_database}}
    user: $(user)
    password: $(password)

- task: FlywayCLI@0
  inputs:
    command: 'migrate'
    url: ${{variables.baseline_database}}
    user: $(user)
    password: $(password)

- task: FlywayCLI@0
  inputs:
    command: 'info'
    url: ${{variables.baseline_database}}
    user: $(user)
    password: $(password)