# YAML Release Pipeline to SQL Server

trigger:
- master

variables:
- group: SQL Server Admin Credentials

stages:
- stage: Build
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job:
    steps:
    - task: FlywayInstaller@0
      inputs:
        flywayVersion: '6.2.0'
    - task: FlywayCLI@0
      inputs:
        command: 'repair'
        url: $(dev_database)
        user: $(user)
        password: $(password)
    - task: FlywayCLI@0
      inputs:
        command: 'baseline'
        url: $(dev_database)
        user: $(user)
        password: $(password)
    - task: FlywayCLI@0
      inputs:
        command: 'migrate'
        url: $(dev_database)
        user: $(user)
        password: $(password)

- stage: Test
  dependsOn: Build
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job:
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # TODO
          
          echo 'Hello world'

- stage: Deploy
  dependsOn: Test
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - deployment:
    environment: 'sqlserver-approval'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: FlywayInstaller@0
            inputs:
              flywayVersion: '6.2.0'
          - task: FlywayCLI@0
            inputs:
              command: 'repair'
              url: $(prod_database)
              user: $(user)
              password: $(password)
          - task: FlywayCLI@0
            inputs:
              command: 'baseline'
              url: $(prod_database)
              user: $(user)
              password: $(password)
          - task: FlywayCLI@0
            inputs:
              command: 'migrate'
              url: $(prod_database)
              user: $(user)
              password: $(password)