# FlyWayDB Demo Pipeline

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo FlyWayDB on Azure DevOps Demo
  displayName: 'Connect to Database and Report Status'

- task: FlywayInstaller@0
  inputs:
    flywayVersion: '6.2.0'

- task: FlywayCLI@0
  inputs:
    command: 'info'
    url: $(connection_string)
    user: $(user)
    password: $(password)